# Generated by Django 5.2.7 on 2025-10-14 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex or CSS color value used to render the department on the floor plan.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="Unique slug used to identify the desk in URLs and the UI.",
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "left_percentage",
                    models.FloatField(
                        help_text="Horizontal position (0-100) relative to the floor plan container."
                    ),
                ),
                (
                    "top_percentage",
                    models.FloatField(
                        help_text="Vertical position (0-100) relative to the floor plan container."
                    ),
                ),
                (
                    "width_percentage",
                    models.FloatField(
                        help_text="Width (0-100) relative to the floor plan container."
                    ),
                ),
                (
                    "height_percentage",
                    models.FloatField(
                        help_text="Height (0-100) relative to the floor plan container."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="floorplan.department",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="BlockOutZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("is_permanent", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                (
                    "desks",
                    models.ManyToManyField(
                        related_name="block_zones", to="floorplan.desk"
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "name"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("desk", "Desk"), ("wfh", "Work From Home")],
                        default="desk",
                        max_length=10,
                    ),
                ),
                ("assignee_name", models.CharField(max_length=200)),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("is_permanent", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                (
                    "desk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="floorplan.desk",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "assignee_name"],
            },
        ),
    ]
